### ISSUE TITLE
Step4 error: run_coverage_analysis

### ISSUE THREAD

**Issue by Juniperlus** [MatteoSchiavinato/manticore#1]
Hi 
I am running manticore on my data it works well till the step 4 in which I have parentA.whole.depth and parentB.whole.depth
however it exit the pipeline and gives the following error:

Traceback (most recent call last):
  File "./manticore", line 1566, in <module>
    status = run_coverage_analysis(	script_dir,
  File "./manticore", line 784, in run_coverage_analysis
    "--beds", " ".join(bed_files),
TypeError: can only join an iterable

please let me know how I can solve this problem 

Thank you

**Comment by MatteoSchiavinato** [comment]
Hi, 
By looking at the error, my first suspicion is that you used the "--beds" argument without passing any actual BED file. 
Could you paste the exact command you used, with all the arguments and paths?

**Comment by Juniperlus** [comment]
hello
thank you for your reply,
I used this simple command
./manticore --species-name hybrid --reads /home/user/data/parentA-R1.fastq.gz,/home/user/data/parentA-R2.fastq.gz /home/user/data/parentB-R1.fastq.gz,/home/user/data/parentB-R2.fastq.gz --names parentA parentB --reference ./hybrid-chromosomes.fasta --output-dir ./test --hisat2-path /home/user/hisat2-master/hisat2

I didn't specified --beds in the argument and I don't find in the output folders any BED file
Thank you

**Comment by MatteoSchiavinato** [comment]
I have committed a new version to the repository. Please try to clone it again and restart it! I think what you found was an actual missing if condition, whereby the absence of a BED file was not properly handled. Let me know if it works!

**Comment by Juniperlus** [comment]
Hi Matteo,

thank you for adding an updated version, I think this step was solved but it was exiting while running "analyze-windows.py". I copy the error message here:
**### [Mon Oct 31 07:48:39 2022] Calculating windows and position ranges ... DONE
[Mon Oct 31 07:48:39 2022] Computing length of features within windows ... DONE
Traceback (most recent call last):
  File "/home/user/manticore-master/src/analyze-windows.py", line 750, in <module>
    for region in args.beds_names:
TypeError: 'NoneType' object is not iterable**

**Comment by MatteoSchiavinato** [comment]
Hi,
Good to know the other is fixed. This one seems like the same issue. I will work on it this morning and get back at you when the new version has been committed!

**Comment by MatteoSchiavinato** [comment]
I think I have fixed all the bugs related to this. It was harder than I expected, thanks for bringing them up. Could you try to reclone it and use it? It worked with my toy dataset. I will close this issue for now, feel free to reopen it if it isn't working as expected.
